version: '3.8'

services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT=/data/db
    user: "999:999"
    volumes:
      - /mydata:/data/db  
    networks:
      - my-network
    ports:
      - '27017:27017' #Expose mongodb to outside docker container (not recommanded)


  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://admin:password@mongodb:27017/admin?authSource=admin
    depends_on:
      - mongodb
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

